server:
  port: 8010
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'