server:
  port: 8033
spring:
  application:
    name: server-zuul
eureka:
  # 配置开启健康检查
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # 指定注册中心的地址
  instance:
    # IP地址优先
    preferIpAddress: true
zuul:
  routes:
    api-ribbon:
      service-id: ribbon-consumer
      path: /api-ribbon/*
    api-feign:
      service-id: feign-consumer
      path: /api-feign/*